APP:
  NAME: conference
  VERSION: 1.0.0
  DESCRIPTION: conference
MYSQL:
  HOST: 127.0.0.1
  PORT: 3306
  USER: root
  PASSWORD: 7220427x
  DATABASE: conference
JWT:
  SECRET_KEY: 203EFEC5-DA59-4A66-9613-C2FC43175B53
  ALGORITHM: HS256
  EXPIRE_MINUTES: 360
